version: "3.1"
services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: ${APP_NAME}-nginx
    working_dir: /usr/share/nginx/html
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - ${APP_PORT_EXPOSED}:${APP_PORT}
  postgres:
    image: postgres:12.1
    container_name: ${APP_NAME}-postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT_EXPOSED}:${DB_PORT}
  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    container_name: ${APP_NAME}-php-fpm
    working_dir: /usr/share/nginx/html
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
